name: Run Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout&v3
      - name: Setup Node
        uses: action/setup-node@v3
      - run: npm ci
      - run: npm test
